apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: longhorn-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  project: default
  source:
    chart: longhorn
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
